# Settings.yml
---
conf.py:
  project: 'Templating Tutorial: Basics'
  copyright: 2011-2014
  version: 1.0.0
  release: 1.0.0
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference
    - null
    t3tssyntax:
    - http://docs.typo3.org/typo3cms/TyposcriptSyntaxReference
    - null
    t3ts45:
    - http://docs.typo3.org/typo3cms/TyposcriptIn45MinutesTutorial
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Tutorial-Templating
    github_branch: latest
  latex_documents:
  - - Index
    - t3templating.tex
    - Templating Tutorial$\colon$Basics
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
